theme: jekyll-theme-minimal

# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- collaborations.md  
- tech.md
- updates.md  

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: Shantel A. Martinez
description: Wheat Molecular Genetics | Preharvest Sprouting
logo : https://github.com/shantel-martinez/Lab_Resources/blob/master/example_img/wheatBWcrop.jpg?raw=true
url: "https://shantel-martinez.github.io/" # Site url, also used in jekyll-seo-tag
# baseurl: ""
# repo: "https://github.com/shantel-martinez/shantel-martinez.github.io"
email: "shantel.a.martinez@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
# css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Research
  url: ./research.html
- title: Talks
  url: ./talks.html
- title: CV
  url: ./CV.html
- title: Resources
  url: ./resources.html
- title: R Protocols
  url: https://shantel-martinez.github.io/Rmd%20Protocols/R%20Protocols.html
- title: Lab Protocols
  url: https://shantel-martinez.github.io/Rmd%20Protocols/Lab%20Protocols.html

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/s_amealia
  LinkedIn: https://www.linkedin.com/in/shantel-a-martinez/
  GitHub: https://github.com/shantel-martinez


